WildernessLabs/Documentation

Samples/Netduino/GlitchFilter/index.md

Changed the pin enum used to reference the onboard switch.
Two different Pins enums were used - Pins and Cpu.Pins.  Changed the InputPort to use the Pins enum for consistency.  Also, end users should really be using the pins enum.

Change Cpi.Pins reference to Pins reference.

---

Netduino/Getting_Started/index.md
README.md
_site/Netduino/Getting_Started/index.html

Initially just adjusting Markdown to get some bulleted lists to render correctly on the [Getting Started page](http://developer.wildernesslabs.co/Netduino/Getting_Started/#visual-studio), and fix a quick typo.
Once I tried to preview it, though, I couldn't get the site to run locally without a few more steps, so I added the steps I had to follow to get Jekyll to serve locally.
I also committed the resulting Jekyll-generated HTML files, since they were being tracked by Git.
Page currently: http://developer.wildernesslabs.co/Netduino/Getting_Started/#visual-studio
After changes:

Add more localhost install steps and tweak some Markdown formatting

---

_includes/footer.html

There are several places where the prior username is present, but it appeared they might all be in generated HTML. I'm hoping fixing it in the footer include will be sufficient, but I have a find-replace ready to go, if needed.

Update Twitter handle.

---

docs/Netduino/Input_Output/File_Storage/index.md

There was a mix of `Method()` and `Method ()`, so I made them all match the current default in VS2015 of no space between name and invocation.

Unify code whitespace

---

docs/Meadow/Getting_Started/Deploying_Meadow/index.md

Added link to Scott Hanselman blog post about a common error on Windows 10 flashing through USB.
Also separated lines in dfu-util call to be more PowerShell friendly.

Windows tip and PowerShell compatibility

---

docfx/api-override/Meadow.Foundation/Meadow.Foundation.Displays.Lcd.CharacterDisplay.md

The CharacterDisplay sample doesn't work currently because the last two constructor arguments (rows and columns) are reversed. I've updated it with named arguments to avoid this in future. It also uses AppBase<> instead of App<>.

Fix Displays.Lcd.CharacterDisplay sample

---

docfx/api-override/Meadow.Foundation/Meadow.Foundation.Displays.LED.SevenSegment.md

Fixed the sample so it compiled and updated it for common cathode. The diagram is wiring the common pins to ground so I think this should be a common cathode seven segment display. I changed the code to reflect that as well as the documentation. It looks like the TEA5767 is a radio so I changed the reference to what I tested this on, a common cathode 5161AS.

Update SevenSegment Display documentation

---

docs/Meadow/Meadow.Foundation/Peripherals/index.md

Description of Temt6000 was incorrectly describing it as a I2C infrared, ultraviolet, and ambient light sensor. Changed to Analog light sensor.

Update index.md - Changed description of Temt6000 to Analog light sensor

---

docs/HackKit/index.md

This change corrects the model number of the Color LCD Display part from "ST7899" to the correct value of "ST7789".

Corrected the Color LCD Display model number

---

docs/Meadow/Getting_Started/Hello_World/index.md
docs/Meadow/Meadow_Basics/Meadow_CLI/index.md

Simple updates to reference Meadow.CLI.exe instead of MeadowCLI.exe

updates to fix Meadow.CLI naming/reference in Meadow_Basics/Meadow_CLI/ Also updated Hello_World documentation with latest Template code example

---

docs/_includes/TopNav.html

It seems the https://www.wildernesslabs.co/meadow no longer exists with the new web site - perhaps should link to https://www.wildernesslabs.co/developers ? :bowtie: :mag_right: :link:

Fix broken Meadow link

---

docfx/api-override/Meadow.Foundation/Meadow.Foundation.Servos.Servo.md

The text from the PiezoSpeaker documentation has been incorrectly used in the servo documentation.

Correct copy and paste error in servo introduction paragraph

---

docfx/api/Meadow.Foundation/index.md
docfx/api/Meadow/index.md

Discovered a typo while reviewing documentation.  Search found it is two places.
"Foudnation" --> "Foundation"

typo correction: Foudnation

---

README.md

Ran into a few quirks on a fresh local Jekyll setup on Windows.
1. I had to start a new shell to get access to `ridk` as well, so I'm wondering if the tip is shown a step too late. I moved it up a step.
> \> ridk install
> ridk: The term 'ridk' is not recognized as a name of a cmdlet, function, script file, or executable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
1. I also ran into an issue with `ridk` itself using an old install of MSYS2 [requiring a workaround via Chocolatey](https://stackoverflow.com/a/64396724/48700).
1. And with the OS steps kind of blending together, I restructured the headers/tabs to make it easier to see where things grouped.
1. [Unrelated] Corrected the casing on `PowerShell` (per [product …

Update for latest Windows local install quirks

---

docs/Hardware/Tutorials/Electronics/Part5/Resistive_Sensor_Lab/index.md

As described in #315, I found a weird Unicode character in the table that was breaking the rest of the page from rendering.
After getting local browser working (with PR #314 resulting), I was able to verify the rest of the page being processed into the resulting HTML now. (Though that table's long headers appears to make rendering a challenge, regardless.)
For a before shot, see the screenshot in #315.
{Fixes #315}

Part 5, Resistive Sensor Lab: Fix page truncation

---

docs/Meadow/Meadow.OS/Configuration/index.md

Add Application Configuration instructions and options

---

docs/Meadow/Meadow.OS/Automatic_Restarts/index.md
docs/Meadow/Meadow.OS/Configuration/Application_Settings_Configuration/index.md

{This PR align docs with changes in WildernessLabs/Meadow.Core#184, if/when it is merged.}
Aligning the two app restart variables to the same verb.

Update restart config variable names for proposed API change

---

docs/Meadow/Meadow.OS/Configuration/index.md
docs/Meadow/Meadow_Basics/Apps/index.md

Cleaned up the main configuration doc to be much cleaner, and then linked to it from the App docs with a high-level summary.

Config connection to App docs

---

docs/_layouts/ElectronicsTutorial.html
docs/_layouts/Hardware.html
docs/_layouts/Meadow.html
docs/_layouts/Netduino.html
docs/_layouts/Page.html
docs/_layouts/Samples.html

[DO NOT MERGE: I need to test this some more locally to make sure nothing looks too unusual. It's possible that some styling or structure may be based around the side-effects of this HTML hiccup.]
This fixes code that generates `<span></small>` mismatch in HTML generation.
Example: http://beta-developer.wildernesslabs.co/Meadow/Meadow_Basics/Apps/
In source, renders this section:
```html
<h1>Meadow Applications</h1>
<p class="header-interior__subtitle"><span>Meadow Basics</small></p>
```

[DO NOT MERGE] Fix mismatched start/end element

---

docs/Meadow/Getting_Started/Deploying_Meadow/index.md
docs/Meadow/Meadow_Basics/Troubleshooting/index.md
docs/Meadow/Meadow_Basics/Troubleshooting/macOS/index.md
docs/_includes/MeadowNavigation.html

Troubleshooting additions

---

docs/HackKit/Contents/index.md
docs/Meadow/Getting_Started/Hello_World/index.md
docs/Meadow/Meadow.OS/Networking/Antenna/index.md
docs/Meadow/Meadow.OS/Networking/index.md
docs/Meadow/Meadow_Basics/Hardware/F7v2/index.md
docs/Meadow/Meadow_Basics/Hardware/index.md
docs/Meadow/Meadow_Basics/IO/Analog/index.md
docs/Meadow/Meadow_Basics/IO/Digital/PWM/index.md
docs/Meadow/Meadow_Basics/IO/Digital/Protocols/I2C/index.md
docs/Meadow/Meadow_Basics/IO/Digital/Protocols/SPI/index.md
docs/Meadow/Meadow_Basics/IO/Digital/Protocols/UART/index.md
docs/Meadow/Meadow_Basics/IO/Digital/index.md
docs/Meadow/Meadow_Basics/IO/Power/index.md
docs/Meadow/Meadow_Basics/IO/index.md
docs/Meadow/Meadow_Basics/Status/index.md
docs/Meadow/Meadow_Basics/Troubleshooting/index.md
docs/Meadow/Release_Notes/Beta6/index.md

Evaluated anywhere we were using "F7 Micro" and updated to "F7 Feather" where it seemed more appropriate. Also same for "Core Compute Module" to "Core-Compute Module" to align with formal product name.
The only usage of "F7 Micro" left was in the [Troubleshooting section](http://beta-developer.wildernesslabs.co/Meadow/Meadow_Basics/Troubleshooting/#error-when-flashing-meadow-windows) where it accurately reflects the device name in Device Manager and Zadig.
(Sorry for the diff noise as I also fixed a lot of typos and Markdown warnings.)

Update F7 Micro and Core-Compute usage

---

docs/Meadow/Meadow.OS/Configuration/OS_Device_Configuration/index.md

Add documentation to show how to enable debug compilation via Mono to be able to see line numbers in runtime exceptions [at the cost of performance].
This appears to only impact exception stack trace data, not any of the default Meadow console logging.
No logging is done to indicate that `--debug` was used. This would be a worthwhile line in case someone accidentally leaves it on.
It doesn't seem like these two parameters have any issues being combined.

Add Mono debug details

---

docs/Hardware/Tutorials/Electronics/Part6/Support_Files/Rectification_Circuit.svg

Fixes #198 
I did a quick adjustment to the diode element's `rotate` transformation operations to manually flip things.

Rotate two misaligned diodes

---

docs/Meadow/Meadow.OS/Automatic_Restarts/index.md

I'd ultimately like to include a sample piece of code for the long-sleep limitation, ideally embedded via Mirid from a compiled sample somewhere, but this would be a good start.

Add watchdog considerations

---

docfx/api-override/Meadow.Foundation/Meadow.Foundation.Relays.Relay.md

Hoping this fixes what's going on here currently:

Fix broken image tag

---

docs/Meadow/Getting_Started/Getting_Started_Core-Compute_Module/index.md
docs/_includes/MeadowNavigation.html

A few CCM and dev kit details, but mostly links to existing docs where they are equivalent with Feather boards.
Also a TOC entry, though we may want to tweak the display text based on length and how it renders.

Initial getting started for Core-Compute module and dev kit

---

docs/Meadow/Meadow.OS/Configuration/OS_Device_Configuration/index.md
docs/Meadow/Meadow.OS/Core-Compute_SD_Card/index.md

Upcoming release requires informing the Meadow OS when SD card hardware is present and needed. This adds the `SdStorageSupported` config information to the `meadow.config.yaml` docs.

Add new SdStorageSupported config info

---

docs/Meadow/Meadow.Foundation/Peripherals/index.md

[Part of #407 effort]
Removed the old blanket peripheral page (now a link to the Wii section). And updated the individual driver rows in that Wii section to point to their own pages.

Update Wii extension peripheral links

---

docfx/api-override/Meadow.Foundation/Meadow.Foundation.Displays.ePaper.Epd1in54.md
docfx/api-override/Meadow.Foundation/Meadow.Foundation.Displays.ePaper.Epd1in54b.md
docfx/api-override/Meadow.Foundation/Meadow.Foundation.Displays.ePaper.Epd1in54c.md
docfx/api-override/Meadow.Foundation/Meadow.Foundation.Displays.ePaper.Epd2in13.md
docfx/api-override/Meadow.Foundation/Meadow.Foundation.Displays.ePaper.Epd2in13b.md
docfx/api-override/Meadow.Foundation/Meadow.Foundation.Displays.ePaper.Epd2in13b_V4.md
docfx/api-override/Meadow.Foundation/Meadow.Foundation.Displays.ePaper.Epd2in7b.md
docfx/api-override/Meadow.Foundation/Meadow.Foundation.Displays.ePaper.Epd2in9.md
docfx/api-override/Meadow.Foundation/Meadow.Foundation.Displays.ePaper.Epd2in9b.md
docfx/api-override/Meadow.Foundation/Meadow.Foundation.Displays.ePaper.Epd4in2bc.md

This will add an override detailing the underlying driver for the WaveShare drivers that are just wrappers for other display drivers.

WaveShare API overrides

---

docs/Meadow/Meadow.OS/RTC/index.md

Fixes #255 in docs, but still requires changes to Hackster.
@jorgedevs Can you update the `Device.SetClock` uses here to align with the updated [sample source](https://github.com/WildernessLabs/Meadow.Project.Samples/blob/main/Source/Hackster/MeadowClock/MeadowApp.cs#L44-L58) using `Device.PlatformOS.SetClock`.

Update SetClock to new namespace

---

.github/workflows/jekyll.yml
docs/Meadow/Meadow_Basics/Apps/Sleep/index.md

Upgraded to RC-3 (v0.9.6.3) this evening - it broke all my apps using SetClock(). 
Used the object browser to discover that SetClock has been moved from Device.SetClock() to Device.PlatformOS.SetClock()

RC-3 (v0.9.6.3) moved Device.SetClock() to Device.PlatformOS.SetClock()

---

docs/Meadow/Meadow.OS/RTC/index.md
docs/Meadow/Meadow_Basics/Apps/Sleep/index.md

The `SetClock` method has moved out of the top-level `Device` into `Device.PlatformOS`

Update Device.SetClock to use Device.PlatformOS

---

docs/Meadow/Getting_Started/Getting_Started_Linux/index.md
docs/_includes/MeadowNavigation.html

Covering an initial use case of Meadow.Linux: developing on your local dev machine, then deploying and running the app on a remote Linux device. (There are so many other paths to take which we can document next, such as local dev through a remote VS Code Server session on the Linux device directly.)
* Background and supported devices (pulled from existing GitHub README docs)
* Dev and Linux device prerequisites
* Building a Hello, World Meadow.Linux app
* Converting a regular Meadow app to M.Linux
* Next steps

Meadow.Linux - initial getting started

---

docs/Meadow/Meadow.OS/Configuration/Application_Settings_Configuration/index.md
docs/Meadow/Meadow.OS/Updates/index.md

* Added prereq for `meadow cloud login`
* Made code blocks part of their respective steps, now numbered
* Cleaned up Markdown warnings
* Added config details to Application Config page with link to OtA docs

Add login prereq and Markdown adjustments

---

docs/index.md

This is probably worth pushing to `main` as well, but here's an edit to get added to the Upcoming Events page in `develop`.
Beta: http://beta-developer.wildernesslabs.co/#upcoming-events
Live: https://developer.wildernesslabs.co/#upcoming-events

Add DevCamp 2023 to Upcoming Events

---

docs/Meadow/Getting_Started/Getting_Started_Linux/index.md

Without this extra step, `dotnet` commands will say `command not found`.

Add dotnet to path

---

docs/index.md

Switching the past event link to the YouTube recordings.
We are still waiting on a unified DevCamp 2023 playlist (vs. the current Day 1 and Day 2 lists), but this is roughly the edit we need.

Switch DevCamp from registration to recording list

---

docfx/api-override/Meadow.Foundation/Meadow.Foundation.Displays.Uc1609c.md

Not sure what the old `^M` character was, but this makes it a proper set of line breaks.

Fix abnormal whitespace character

---

.github/workflows/docfx-develop.yml

Accidentally fixed all the other pre-merge stuff _but_ the name itself.

Proper name for Docs API workflow

---

docs/Meadow/Meadow.OS/Cellular/index.md

Just to replace the ```Csharp``` for ```csharp``` that seemed to affect the sample code style

Fix Cell sample style

---

docs/Meadow/Meadow.OS/Configuration/OS_Device_Configuration/index.md

Updated the NTP refresh period option name and also changed the JIT comments and flipped this to interpreted mode as JIT is not the default.

Updates to configuration options

---

.github/workflows/docfx-develop.yml

Altered from invalid expectations to reality. We trigger this Action manually from the `main` branch, but targeting the `developer` content.

Fix beta API condition and use of `develop`

---

.github/workflows/jekyll.yml

This Action was named identically to the [beta one](https://github.com/WildernessLabs/Documentation/blob/main/.github/workflows/jekyll-beta.yml), which could cause some confusion.
This should fix that in the Action list, too.

Fix Action name mismatch

---

docs/Meadow/Meadow.OS/Cellular/index.md

Minor fix related to correcting the Reserved Pin name, which should be `A3` instead of `A03`.

Fix small issue on the reserved pin name

---

docfx/docfx.json

Trying to resolve broken link for Tsa9548a.
https://developer.wildernesslabs.co/Meadow/Meadow.Foundation/Peripherals/#ics
Currently failing for this URL because we were excluding it.
http://developer.wildernesslabs.co/docs/api/Meadow.Foundation/Meadow.Foundation.ICs.IOExpanders.Tca9548a.html

Remove Tsa9548a exclusion to test DocFX

---

docfx/api-override/Meadow.Foundation/Meadow.Foundation.ICs.IOExpanders.Mcp23x08.md
docfx/api-override/Meadow.Foundation/Meadow.Foundation.ICs.IOExpanders.Mcp23xxx.md

Promoting an abstracted version of the MCP23008 override to the parent MCP23XXX API docs, that then links out to each of the chip family and chip-specific pages.

Add generic Mcp23xxx API override

---

docfx/api/Meadow/index.md

[Fixes #506]
Found the API page under Meadow.Foundation, which appears to be how our DocFX system is generating things.

Fix broken Meadow.Hardware link

---

docs/Meadow/Meadow_Basics/IO/Digital/Protocols/UART/index.md

[[Per thread in Slack](https://wildernesslabspublic.slack.com/archives/CQWD660E8/p1692117942336799)]
The API for creating serial ports changed. This updates the two main ones.

Update to GetSerialPortName methods

---

docfx/docfx.json

We were cloning the repos for the DocFX .NET build side of things, but weren't telling it to generate docs pages from those repos.

Generate API docs for Meadow.Contracts, .Logging, and .Units

---

docs/Hardware/Reference/BitBanging/index.md
docs/Hardware/Tutorials/Electronics/Part4/Resistance/index.md
docs/Hardware/Tutorials/Electronics/Part4/Review/index.md
docs/Hardware/Tutorials/Electronics/Part6/LEDs/index.md
docs/Hardware/index.md
docs/Netduino/Input_Output/Digital/I2C/Reading/index.md
docs/Netduino/Input_Output/Digital/I2C/Writing/index.md
docs/Netduino/Input_Output/Digital/I2C/index.md
docs/Netduino/Input_Output/Digital/PWM/index.md
docs/Netduino/Input_Output/Digital/SPI/Writing/index.md
docs/Samples/Netduino/RGB_Blinky/index.md
docs/_includes/HardwareNavigation.html

Should fix #484 
There was a restructuring that didn't get accounting in the existing URLs. This should update to that.
/Hardware/Reference/Components
...moved to...
/Hardware/Circuits/Components
There may be others that need fixing from that [same commit](https://github.com/WildernessLabs/Documentation/commit/5f31b0170b4954120b242ddf9b6596c385e1b64f).

Update links to folder changes

---

docfx/api-override/Meadow.Foundation/Meadow.Foundation.Leds.Led.md

Fixes #461
I restored the deleted markup that was accidentally removed and added new alt text.

Repair broken img tag and add alt text

---

docs/Meadow/Meadow.Foundation/Libraries_and_Frameworks/MicroGraphics/index.md

Add details about embedding image assets for #525.
@adrianstevens I think the section right before this is possibly outdated as well.  I'm not finding any `DrawBitmap` method on the MicroGraphics object.

Add details on image embedded resources

---

docs/Meadow/Meadow.OS/Networking/index.md

Added information on how to use and which impacts when setting `ClearDefaultCredentials ` on  `wifi.config.yaml`
```
Credentials:
Ssid: YourSSID
Password: SSIDPassword
ClearDefaultCredentials: true
```

New property to clear the last credentials stored

---

docs/Meadow/Meadow.OS/Networking/index.md

Removing the link` Mapple Server` which pointed to Meadow.Foundation Docs, but since the link right is correct we can remove it.

Removed the link Mapple Server

---

docs/api/Meadow.Foundation/Meadow.Foundation.Sensors.Atmospheric.Bme688.md

Couldn't find a BME688-specific image, but falling back on the BME680 image since the wiring is almost identical.
{fixes WildernessLabs/Meadow_Issues#440}

Fix wiring diagram image src

---

docs/Meadow/Meadow.OS/Cellular/index.md

Fixes WildernessLabs/Meadow_Issues#463
Looks like it was supposed to be a link to a later header in this same page. This _should_ do it, but it's hard to know until it is deployed.

Fix link to page anchor

---

docs/Meadow/Getting_Started/Deploying_Meadow/index.md

It appears the old `/Getting_Started/Deploying_Meadow/` page is still being hosted, though it is no longer part of the repo. (Perhaps our deployments do not delete files as they are removed from the repo.)
In order to avoid the duplicate, outdated content, this will deploy a file in its place that directs any folks with the old link to the `/Deploying_Meadow.OS/` page instead.

Redirect over legacy Deloying_Meadow page

---

docs/Meadow/Meadow.Cloud/Device_Provisioning/index.md

Adding a missing one-time SSH setup prereq step for provisioning hosts that run Meadow.Desktop apps.

Add M.Desktop SSH prereq

---

docs/Hardware/Reference/Components/Common/index.md
docs/Hardware/Reference/Components/index.md

{Fixes #732}
The original link is a 404.
The new link that reflects the page structure was an empty page.
So, I added the basic links to sub-sections as well.

Fix link and add missing content

---

docs/Meadow/Meadow.Foundation/Getting_Started/index.md

{fixes #586}
The old link went to the Feather getting-started. This goes to the general getting started section.

Update getting-started link

---

docs/Meadow/Getting_Started/Deploying_Meadow.OS/index.md

{fixes #549}
Adding a notes section about data or poor-quality cables and potential issues with unpowered USB hubs, similar to the sections from the Troubleshooting page.

Add cable/power warnings

---

docs/Meadow/Meadow.OS/Networking/index.md

- https://github.com/WildernessLabs/Meadow_Issues/issues/725
Many users seem to use the same config as in the documentation, but forget to properly set the IP address, since using a static IP address is a bit more complicated - you need to find your gateway, netmask, and choose an IP address within your local network that is not currently already in use. 
For this reason, I believe that would be easier for the new user trying to use ethernet, to use the DHCP, since the user doesn't need to take all of it into consideration, given that the DHCP will set everything automatically.

Minor fix on Ethernet config sample

---

docs/Meadow/Meadow_Basics/IO/Digital/Protocols/CAN/index.md
src/sidebars/meadowOsSidebar.js

Ported the initial CAN page @ctacke created to the right location and added it to the sidebar.

Add CAN page

---

docs/Meadow/Meadow.Foundation/Libraries_and_Frameworks/TensorFlowLite/index.md
docs/Meadow/Meadow.OS/AI/index.md
src/sidebars/meadowOsSidebar.js

Added an AI overview on Meadow guide that links to the TFlite docs. Also did some minor style cleanups to the TFLite doc.

Ai overview guide

---

docs/Meadow/Getting_Started/Updating_Meadow/index.md

meadow `download os` & `write os` appear to have been replaced by `firmware download` & `firmware write`

Meadow updating docs seem to be out of date?

---

docs/Meadow/Meadow_Basics/IO/Digital/index.md

Updated CreateDigitalInterruptPort and CreateDigitalInputPort.
CreateDigitalInputPort previously included parameters for CreateDigitalInterruptPort.
Note that there is still an ambiguity in Glitch and Debounce filters as it states '0' to disable. Should this be 'TimeSpan.Zero'?

Digital IO Docs

---

docs/Meadow/Meadow.Cloud/OtA_Updates/index.md

CLI V2 needs verb "cloud" when creating and uploading the MPAK.

update command line to create and upload MPAK to CLI V2

---

docs/Meadow/Meadow.Cloud/OtA_Updates/index.md

manual tie-in code should still be looked at to show either cancelling the update, or scheduling it for later.

Updated docs for automatic OtA

---

docs/Meadow/Meadow_Tools/Meadow_CLI/index.md

[via [conversation on Wilderness Labs Public Slack](https://wildernesslabspublic.slack.com/archives/CQWD660E8/p1754415933605919)]
I can't quite tell if I got the Getting Started link set up correctly. We might need to test it in the preview build.

Add note about installing Meadow templates
