WildernessLabs/Documentation

Samples/Netduino/GlitchFilter/GlitchFilter/Program.cs

Aligned source code with the index file.

Made program.cs match index.md

---

Hardware/Circuits/OHMs_Law/index.md
Hardware/Circuits/Resistors/index.md

Added information about Ohms Law - maybe need to add ohms law triangle.
Initial resister informaiton.

Initial Ohms Law and Resister Documents

---

Netduino/About/Downloads/index.md

Fixing heading sizes.

---

DocumentationRoadmap.md
Netduino/Input_Output/Digital/index.md

Updated roadmap to indicate I2C and SPI changes.
Minor updates to Digital IO master index, expanded some example, repointed links.

Updated roadmap and Digital IO index

---

Netduino/Input_Output/Digital/PWM/index.md

Just a small copy edit I noticed while reading :)

pwm: fixed spelling error (Ouput/Output)

---

Hardware/Tutorials/Electronics/Part1/Atoms/index.md

Just adjusting the expansion a little. If I'm doing my decimal-moving math correctly, the original had a couple extra zeros.
```
18.066 x 10^24 = 18,066,000,000,000,000,000,000,000
[moving decimal    .>>3 >>6 >>9 >12 >15 >18 >21 >24]
```

Adjust expansion of scientific notation in atoms discussion.

---

Samples/Netduino/RGB_Blinky/index.md

I mostly just noticed the errant comma and did a quick pass of things.

[RGB_Blinky] Tweak some wording/punctuation.

---

docs/Hardware/Tutorials/Electronics/Part1/Electrical_Current/index.md

Update index.md swapping hole with electron

---

docs/Netduino/Getting_Started/index.md

Just saw a few word casing issues to fix and the missing alt tag on the animated GIF.

Few casing fixes and alt tags

---

docs/Hardware/Tutorials/Electronics/Part4/Review/index.md
docs/Hardware/Tutorials/Electronics/Part5/Voltage_Divider_Practicals/index.md
docs/Samples/index.md

minor case issue was causing the link to not resolve

Some link and content revisions

---

docs/Meadow/Getting_Started/Hello_World/index.md

Matching it up with the class name.

Fix a constructor typo

---

docs/Meadow/Getting_Started/Hello_World/index.md

Saw some weird rendering issues and noticed some list syntax needed a little adjusting.
Also, a missing backtick.

Fix some Markdown formatting

---

docfx/api-override/Meadow.Foundation/Meadow.Foundation.Leds.Led.md

Update documentation to compile with current API.  Add a sleep at the end so the 'on' at the start of the while loop doesn't get skipped.

Update LED documentation

---

docfx/api-override/Meadow.Foundation/Meadow.Foundation.Leds.Led.md

Put ticks on their own line to break close the code block

Fix the ticks

---

docs/Meadow/Meadow_Basics/Meadow_CLI/index.md
docs/Meadow/Meadow_Basics/Troubleshooting/index.md
docs/_includes/MeadowNavigation.html

Added some basic troubleshooting in order to help early beta testers.

Troubleshooting guide

---

docs/Hardware/Tutorials/Electronics/Part2/Amount_and_Force/index.md

different -> difference
(P.S. Thank you for writing such a wonderful tutorial!)

fix small typo

---

docs/Meadow/Getting_Started/Deployment/Linux/index.md

* List packages that are needed as text.
* Replace multiple broken commands with one working.

Fix broken package commands for test app on Linux

---

docfx/api-override/Meadow.Foundation/Meadow.Foundation.Audio.PiezoSpeaker.md
docs/Meadow/Meadow.Foundation/index.md

Fixed HelloBlinky so that it would compile, use the correct PwmLed method and be able to copy/paste for a working sample.

Hello Blinky would neither compile nor run the onboard LED

---

docs/Meadow/Getting_Started/Hello_World/index.md

Fix code sample in getting_started: hello_world.

---

CNAME
docs/Meadow/Getting_Started/Deploying_Meadow/index.md

Added the instructions for deploying the MeadowOS on Linux (Debian, Ubuntu).

Linux instructions

---

docs/Meadow/Meadow_Basics/Meadow_CLI/index.md
docs/Meadow/Meadow_Basics/Troubleshooting/index.md
docs/Meadow/Release_Notes/Beta3/index.md
docs/Meadow/Release_Notes/Beta4/index.md

Updated WriteFile and DeleteFile commands to match the updated CLI.

Updated WriteFile and DeleteFile to match the updated CLI.

---

docs/_includes/MeadowNavigation.html

Add Linux to Troubleshooting menu

---

docs/HackKit/index.md
docs/Meadow/Release_Notes/Beta4/index.md

Fixed bad link to image gallery example.

Fixed bad link to image gallery example.

---

docs/Meadow/Meadow.Foundation/Unified_GPIO_Arch/index.md

Fix old NetArduino reference to Meadow board

Fix old NetArduino reference

---

docs/index.md

Adding Developer South Coast event information.

Updated events on main page.

---

docs/Meadow/Getting_Started/Deploying_Meadow/index.md

Add note for Windows user to install dfu-util within an admin console.

Add note for Windows user to install dfu-util within an admin console.

---

docs/Meadow/Meadow.OS/Bluetooth/index.md

Added NuGet and GitHub links for another .NET client library for Windows/Mac/iOS/Android

Bluetooth - Add link to 32feet.NET client library

---

docs/Meadow/Getting_Started/Hello_World/index.md

Update getting started page with the new Meadow device List as suggested in #306 by @rcdemski.

Replace Device Panel by the new toolbar list

---

docs/Hardware/Tutorials/Electronics/Part1/Atoms/index.md
docs/Hardware/Tutorials/Electronics/Part1/Electrical_Current/index.md
docs/Hardware/Tutorials/Electronics/Part1/Electromagnetism/index.md
docs/Hardware/Tutorials/Electronics/Part1/Review/index.md
docs/Hardware/Tutorials/Electronics/Part2/Amount_and_Force/index.md
docs/Hardware/Tutorials/Electronics/Part2/Amperage/index.md
docs/Hardware/Tutorials/Electronics/Part2/Source_Load_and_Ground/index.md
docs/Hardware/Tutorials/Electronics/Part2/Voltage/index.md
docs/Hardware/Tutorials/Electronics/Part3/AC_Characteristics/index.md
docs/Hardware/Tutorials/Electronics/Part3/AC_Generation/index.md
docs/Hardware/Tutorials/Electronics/Part3/Review/index.md
docs/Hardware/Tutorials/Electronics/Part4/Calculating_Resistance/index.md
docs/Hardware/Tutorials/Electronics/Part4/Parallel_Resistance/index.md
docs/Hardware/Tutorials/Electronics/Part4/Resistance/index.md
docs/Hardware/Tutorials/Electronics/Part4/Resistor_Lab/index.md
docs/Hardware/Tutorials/Electronics/Part4/Resistor_Power_Rating/index.md
docs/Hardware/Tutorials/Electronics/Part4/Resistor_Tolerance/index.md
docs/Hardware/Tutorials/Electronics/index.md

I did some light editing as I read through Parts 1-4 of the electronics tutorial: mostly adding/removing commas and a few typos. It was a fun read :-)

Tutorials electronics: part1 to part4 markt light edits

---

docs/Meadow/Getting_Started/Deploying_Meadow/index.md

I've regrouped the infos on different sections, one per each development OS.
Please note that:
1. Images from the page [Update USB Driver for ST devices](http://developer.wildernesslabs.co/Meadow/Getting_Started/Update_USB_Driver/) whom info are now contained in this page should be linked from original source and not from my imported images, used in this PR only as bookmark.
2. I've deleted the markup code {:standalone} please add it as needed
3. Double check my English!

Refactoring of the Meadow OS Deployment page

---

docs/Hardware/Tutorials/Electronics/Part5/Circuit_Software/index.md
docs/Hardware/Tutorials/Electronics/Part5/DC_Circuits/index.md
docs/Hardware/Tutorials/Electronics/Part5/Kirchhoffs_Current_Law/index.md
docs/Hardware/Tutorials/Electronics/Part5/Kirchhoffs_Voltage_Law/index.md
docs/Hardware/Tutorials/Electronics/Part5/Level_Shifting_Lab/index.md
docs/Hardware/Tutorials/Electronics/Part5/Resistive_Sensor_Lab/index.md
docs/Hardware/Tutorials/Electronics/Part5/Review/index.md
docs/Hardware/Tutorials/Electronics/Part5/Voltage_Divider_Practicals/index.md
docs/Hardware/Tutorials/Electronics/Part5/Voltage_Division/index.md
docs/Hardware/Tutorials/Electronics/Part6/General_Diodes/index.md
docs/Hardware/Tutorials/Electronics/Part6/LED_Lab/index.md
docs/Hardware/Tutorials/Electronics/Part6/LEDs/index.md
docs/Hardware/Tutorials/Electronics/Part6/Light_Related_Diodes/index.md
docs/Hardware/Tutorials/Electronics/Part6/N-Type/index.md
docs/Hardware/Tutorials/Electronics/Part6/P-N_Junctions/index.md
docs/Hardware/Tutorials/Electronics/Part6/P-Type/index.md
docs/Hardware/Tutorials/Electronics/Part6/Review/index.md
docs/Hardware/Tutorials/Electronics/Part6/Semiconductors/index.md
docs/Hardware/Tutorials/Electronics/Part6/Silicon/index.md

Added some alt text, a few typo fixes, light edits for clarity.
Changes are only to Part 5 and Part 6 of the Electronics tutorial.
No changes to Part 7, Part X, and Part Y as they seem to be unpublished works-in-progress.

Tutorials electronics part5-part6 markt light edits

---

docs/Meadow/Meadow.OS/Configuration/index.md

Add Application Configuration instructions and options

---

docs/Meadow/Meadow_Basics/Apps/Lifecycle_Update/index.md
docs/Meadow/Release_Notes/Release-Candidates/index.md
docs/_includes/MeadowNavigation.html

I wasn't sure if we needed a separate section for project updates and lifecycle changes in the release notes. We can adjust things, though.

App lifecycle update refinements

---

docs/Meadow/Meadow.OS/Configuration/index.md

Reverts WildernessLabs/Documentation#345
oops

Revert "Add Application Configuration instructions and options"

---

docs/Meadow/Meadow.OS/Configuration/Application_Settings_Configuration/index.md
docs/Meadow/Meadow.OS/Configuration/OS_Device_Configuration/index.md
docs/Meadow/Meadow.OS/Configuration/WiFi_Configuration/index.md
docs/Meadow/Meadow.OS/Watchdog/index.md
docs/_includes/MeadowNavigation.html

App settings config restructuring

---

docs/Meadow/Getting_Started/Deploying_Meadow/index.md

Add notice of Homebrew prerequisite

---

docs/Meadow/Getting_Started/Deploying_Meadow/index.md

Did some Markdown fixes, but here are the primary edits.
https://github.com/WildernessLabs/Documentation/pull/353/files#diff-16a76330676531258c63acf54c5ed7f04b7d5c1593b6d52b0e53112febdd17faR141-R148

Deploying Meadow: macOS $PATH fix

---

docs/Meadow/Meadow.OS/Configuration/OS_Device_Configuration/index.md

(Also fixing a reference to the wi-fi config.)

Add JIT config to meadow.config.yaml

---

docs/Meadow/Meadow_Basics/Apps/Lifecycle_Events/index.md
docs/Meadow/Meadow_Basics/Apps/Sleep/index.md
docs/_includes/MeadowNavigation.html

Add lifecycle and sleep events

---

docs/Meadow/Meadow_Basics/IO/Digital/PWM/index.md

Via user-reported issue in Slack.

Update for new typed units

---

docs/Meadow/Meadow.OS/Networking/index.md
docs/Meadow/Meadow_Basics/Status/index.md

SSL validation was added in RC-1.

Remove warning of SSL not being validated

---

README.md

When I read it, I thought we were missing a command since ridk didn't mean MSYS2 to me.

Clarify MSYS2 install step

---

docs/Meadow/Getting_Started/Hello_World/index.md

This option should be a better/faster fit for anyone not using mouse control (e.g., voice navigation).

Add additional toolbar showing option

---

docs/Meadow/Getting_Started/Getting_Started_Core-Compute_Module/index.md

Step labels and link to design repo.

Core-Compute getting started: additional details/edits from review

---

docs/Meadow/Meadow_Basics/Meadow_CLI/index.md

Based on usage / docs in meadow cli v0.90.4

Meadow CLI deploy command args fix

---

docs/Meadow/Getting_Started/Getting_Started_Linux/index.md

Oops...forgot to remove this to-do item after adding the page to the TOC.

Remove completed TODO

---

docs/Hardware/Tutorials/Electronics/Part1/Atoms/index.md

Hopefully I'm right on this... I can see where the confusion might have been... I noticed the original number of 6.02x10^24 looked a bit like [Avagadro's number](https://en.wikipedia.org/wiki/Avogadro_constant), but that's actually 6.02x10^**23.** So that led me to look into it more and I think I have the right numbers in this PR.

Corrected the number of atoms/molecules in a cup of water.

---

docs/Meadow/Meadow.OS/Cellular/index.md
docs/_includes/MeadowNavigation.html

First cell documentation draft focused on the steps to configure the **BG770A Cell Wing** with the **Meadow F7 Feather v2**.

Cell documentation draft

---

docs/index.md

Did a placeholder with the Day 1 playlist. This is the full-camp playlist now.

Full DevCamp YT link

---

.github/workflows/api-docs-develop.yml
.github/workflows/api-docs-production.yml
.github/workflows/jekyll-beta.yml
.github/workflows/jekyll.yml

...replicated and adapted from the beta Action.
Then unified the naming scheme.

Create production API docs Action

---

docs/Meadow/Meadow.OS/Cellular/index.md

**Summary**
This PR aims to add docs related to some features based on the following issues:
- https://github.com/WildernessLabs/Meadow/issues/424
- https://github.com/WildernessLabs/Meadow/issues/416
- https://github.com/WildernessLabs/Meadow/issues/428

Add cell events and scanner docs

---

README.md
docs/Hardware/Reference/Units/Amps/index.md
docs/_includes/Footer.html
docs/_includes/TopNav.html
docs/_layouts/SiteFrame.html
docs/dist/assets/favicon/manifest.json
docs/dist/css/main.css
frontend/css/src/_nav.scss

[[Changes](https://github.com/WildernessLabs/Documentation/pull/498/files#diff-aedab8b5ff00a322e171ef315ffedfc4a481511005a90d40dd1cd1e3ec585765R6-R7)]
Currently, pages _all_ have the same title, which is not ideal for SEO. This system will use the page's title variable for the HTML title. Additionally, all pages have an empty meta description. This system will use the page's subtitle variable. (It's probably not a 100% solution, but it definitely provides better data.)
This is what that looks like in practice for search results, which isn't an ideal user experience.
Going forward, all these pages will use their H1 tag as the page title as well to improve that.
And some search engines put weight on what's in the meta description tag, which has been `""` for all pages up to this point. This …

SEO improvement and various resource path fixes

---

docs/Meadow/Meadow.OS/Configuration/Application_Settings_Configuration/index.md
docs/Meadow/Meadow.OS/Configuration/OS_Device_Configuration/index.md
docs/Meadow/Meadow.OS/Configuration/WiFi_Configuration/index.md
docs/Meadow/Meadow.OS/Configuration/index.md
docs/Meadow/Meadow.OS/Networking/index.md
docs/Meadow/Meadow.OS/SQLite/index.md
docs/Meadow/Meadow_Basics/IO/Analog/index.md
docs/Meadow/Meadow_Basics/IO/Digital/index.md
docs/Meadow/Release_Notes/Beta3/index.md
docs/Meadow/Release_Notes/Beta4/index.md
docs/Meadow/Release_Notes/Beta5/index.md

[Also added a config link for a related wi-fi settings.]

Fix sample repo URLs

---

docs/Meadow/Meadow.OS/Cellular/index.md

Fix minor issues related to the latest cell docs changes.

Fix cellular docs minor issues

---

docs/Meadow/Getting_Started/Hello_World/index.md

Found this while working on a different effort and figured I'd get it upstream.

Fix broken image src

---

docs/Meadow/Meadow.Foundation/Libraries_and_Frameworks/Gps_Gnss_Nmea_Processor/index.md
docs/Meadow/Meadow_Basics/IO/Digital/Protocols/UART/index.md

Update to Device.PlatformOS.GetSerialPortName

---

docs/Meadow/Meadow.OS/Networking/Antenna/index.md
docs/Meadow/Meadow.OS/Networking/index.md

Fixes #256 and #533
Fixed broken link, updated to latest API, and linked to the available sample.

Update antenna API and docs link

---

docs/Meadow/Getting_Started/Deploying_Meadow/index.md

Moved section as suggested in #394.

Windows deployment docs unclear about bootloader mode (Issue #394)

---

docs/Meadow/Meadow.Cloud/Health_Monitoring/index.md
docs/Meadow/Meadow.Cloud/Integrations/AzureEventGrids/index.md
docs/Meadow/Meadow.Cloud/Integrations/index.md
docs/Meadow/Meadow.Cloud/Logs_Events/index.md
docs/_includes/MeadowNavigation.html

Added Azure Event Grid documentation to all the applicable pages.

Added documentation for Azure Event Grid

---

.github/workflows/api-docs-production.yml
.github/workflows/azure-static-web-apps-blue-mushroom-0f697a110.yml
.github/workflows/jekyll.yml
docs/Meadow/Getting_Started/Hello_World/index.md
docs/_layouts/SiteFrame.html

Change URL to the Meadow VS Extension in Hello World (Issue #548)

---

docfx/_exported_templates/default/dist/css/main.css

First step in trying to resolve TOC not working on API docs ([example](https://developer.wildernesslabs.co/docs/api/Meadow/, viewed in a skinny window)).

Sync with non-API stylesheet

---

docs/Hardware/Tutorials/PCB_Tutorial/PCB_Assembly/index.md
docs/Hardware/Tutorials/PCB_Tutorial/PCB_Layout/index.md
docs/Hardware/Tutorials/PCB_Tutorial/Schematic_Design/index.md

Update PCB workshop video embeds to DevCamp 2023

---

docs/Hardware/Tutorials/Electronics/Part1/index.md
docs/Hardware/Tutorials/Electronics/Part2/index.md
docs/Hardware/Tutorials/Electronics/Part3/index.md
docs/Hardware/Tutorials/Electronics/Part4/index.md
docs/Hardware/Tutorials/Electronics/Part5/index.md
docs/Hardware/Tutorials/Electronics/Part6/Semiconductors/index.md
docs/Hardware/Tutorials/Electronics/Part6/index.md
docs/Hardware/Tutorials/Electronics/index.md
src/sidebars/hardwareTutorialsSidebar.js

so far these are all just cleanups that don't break anything, so i vote we merge

Electronics tutorial fixups

---

docs/Meadow/Release_Notes/Release-Candidates/index.md

Part of #638, unifying the message from the prior Sleep page docs and adding the sample for anyone impacted on the old firmware.

Update RC-1 AfterWake logging issue notes

---

docs/Meadow/Meadow_Basics/Apps/index.md
docs/Meadow/Meadow_Basics/IO/Digital/PWM/index.md
docs/Meadow/Meadow_Basics/IO/Digital/Protocols/I2C/index.md
docs/Meadow/Meadow_Basics/IO/index.md
docs/Meadow/Meadow_Basics/Meadow.OS/index.md
docs/Meadow/Release_Notes/Beta3/index.md
docs/Meadow/Release_Notes/Beta4/index.md

@jorgedevs Should be 75-83 in that export spreadsheet.

Fixing various 404s

---

docs/Meadow/Meadow_Basics/Meadow_CLI/index.md

I updated several commands that were still using the deprecated versions.
In this case, I also expanded any parameters to their more descriptive versions, since this is a Basics page.

Update CLIv2 commands

---

docs/Meadow/Getting_Started/Deploying_Meadow.OS/index.md

* fix `meadow config route`
* update link to download .net 8

fix a couple deploy issues

---

docs/Meadow/Meadow_Basics/IO/Analog/High_Speed/index.md
docs/Meadow/Meadow_Basics/IO/Analog/index.md
src/sidebars/meadowOsSidebar.js

New doc: AnalogInputArray

---

docs/Meadow/Meadow.OS/Cellular/index.md

{fixes #644, thank you @fredmbarrett}

Fix variable name mismatch

---

docs/Meadow/Meadow.OS/TLS_Client_Authentication/index.md

- https://github.com/WildernessLabs/Meadow/issues/458
- https://github.com/WildernessLabs/Meadow.Core.Samples/pull/99

Add TLS client auth docs

---

docusaurus-config/theme-config.js

Just removing a TODO that has already been TODONE. We customized the social card in that existing filename.
https://github.com/WildernessLabs/Documentation/blob/main/static/img/docusaurus-social-card.jpg

Remove legacy TODO

---

docs/Meadow/Getting_Started/Deployment/index.md

Link to new page

---

README.md

Adding some guidance to help folks find special sections in the site (navigation and redirects), as well as a couple tips for when things don't work as expected.

Add docs developer tips

---

docs/Meadow/Meadow.Cloud/Device_Provisioning/index.md

Based on [this Reddit discussions](https://www.reddit.com/r/WildernessLabs/comments/1czhfox/comment/l5htmbz/).

Adjust keygen parameters

---

docfx/dfmg/Meadow.Foundation.CompositeDevices/config.yaml

- Added Meadow.Foundation.CompositeDevices

[build-api] Fix foundation api

---

docs/Meadow/Meadow.Cloud/Logs_Events/index.md

Add Meadow.Cloud logging NuGet dependency

---

docs/Meadow/Meadow_Basics/IO/Digital/Protocols/I2C/index.md
docs/Meadow/Meadow_Basics/IO/Digital/Protocols/SPI/index.md

Update SPI and I2C samples

---

docs/Meadow/Getting_Started/Setup/index.md

Update to send users to getting-started directly

---

docs/Meadow/Getting_Started/Assemble_Meadow/index.md

Add note on hole clearance

---

docs/Meadow/Meadow.Cloud/OtA_Updates/index.md

the publish command was missing the 'cloud' part and the collection

Update index.md, fixed publish command

---

docs/Meadow/Getting_Started/Deploying_Meadow.OS/index.md

Meadow v2 changed the meadow command from list ports to port list

Updated meadow command to port list

---

.github/workflows/publish-site-prod.yml
docs/Meadow/Meadow.Foundation/Peripherals/index.md
docs/Meadow/Release_Notes/v2/index.md

Since it only includes the new Bluetooth docs, which are live in the latest Meadow releases, this should be fair game to deploy.

Deploy latest from develop

---

docs/Meadow/Meadow_Desktop/Meadow_Blazor/index.md
docs/Meadow/Meadow_Desktop/Meadow_Linux/index.md
docs/Meadow/Meadow_Desktop/Meadow_Mac/index.md
docs/Meadow/Meadow_Desktop/Meadow_Windows/index.md
src/components/GettingStarted.tsx

Meadow.Blazor

---

docs/Meadow/Meadow_Tools/Meadow_CLI/index.md
docs/Meadow/Release_Notes/v2/index.md

* Template install note on Meadow CLI

Merge latest dev to main

---

docs/Meadow/Meadow.Foundation/Libraries_and_Frameworks/MicroLayout/index.md

Updating samples to the current API name where `ForeColor` is `ForegroundColor`.

Fix ForeColor->ForegroundColor
